# Generated by Django 5.2.8 on 2025-11-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanageruser',
            name='current_conversation_state',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
